on run {daemon_file, agent_file, user}

  set daemon_plist to "/Library/LaunchDaemons/com.carriez.RustDesk_service.plist"
  set agent_plist to "/Library/LaunchAgents/com.carriez.RustDesk_server.plist"
  set daemon_label to "com.carriez.RustDesk_service"
  set daemon_socket to "/tmp/RustDesk-service/ipc_service"
  set helper_base to "/Library/PrivilegedHelperTools"
  set helper_bundle to "/Library/PrivilegedHelperTools/com.carriez.RustDesk_service.bundle"
  set migration_state to "/Library/PrivilegedHelperTools/.com.carriez.RustDesk_service.migration"
  set transaction_lock to "/var/run/com.carriez.service-maintenance.lock"
  set service_source to "/Applications/RustDesk.app/Contents/MacOS/service"
  set custom_source to "/Applications/RustDesk.app/Contents/Resources/custom.txt"
  set prefs_dir to "/Users/" & user & "/Library/Preferences/com.carriez.RustDesk/"

  set daemon_plist_q to quoted form of daemon_plist
  set agent_plist_q to quoted form of agent_plist
  set helper_base_q to quoted form of helper_base
  set helper_bundle_q to quoted form of helper_bundle
  set migration_state_q to quoted form of migration_state
  set transaction_lock_q to quoted form of transaction_lock
  set helper_transaction_template_q to quoted form of (helper_base & "/.com.carriez.RustDesk_service.install.XXXXXX")
  set service_source_q to quoted form of service_source
  set custom_source_q to quoted form of custom_source
  set prefs_toml_q to quoted form of (prefs_dir & "RustDesk.toml")
  set prefs2_toml_q to quoted form of (prefs_dir & "RustDesk2.toml")

  -- Administrator authorization is the first-install trust boundary. The root helper never falls back to application-bundle execution after installation.
  set validate_helper_function to "helper_has_no_acl() { acl_mode=$(/bin/ls -lde \"$1\" | /usr/bin/awk 'NR == 1 { print $1 }') || return 1; [ -n \"$acl_mode\" ] || return 1; case \"$acl_mode\" in *+) return 1;; esac; }; validate_helper_tree() { helper_root=\"$1\"; for helper_dir in \"$helper_root\" \"$helper_root/Contents\" \"$helper_root/Contents/MacOS\" \"$helper_root/Contents/Resources\"; do [ ! -L \"$helper_dir\" ] && [ -d \"$helper_dir\" ] && helper_has_no_acl \"$helper_dir\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_dir\")\" = '0:0:755' ] || return 1; done; helper_bin=\"$helper_root/Contents/MacOS/service\"; [ ! -L \"$helper_bin\" ] && [ -f \"$helper_bin\" ] && helper_has_no_acl \"$helper_bin\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_bin\")\" = '0:0:755' ] || return 1; helper_custom=\"$helper_root/Contents/Resources/custom.txt\"; if [ -e \"$helper_custom\" ] || [ -L \"$helper_custom\" ]; then [ ! -L \"$helper_custom\" ] && [ -f \"$helper_custom\" ] && helper_has_no_acl \"$helper_custom\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_custom\")\" = '0:0:600' ] || return 1; fi; }; validate_helper_transaction() { [ -n \"$helper_transaction\" ] && [ ! -L \"$helper_transaction\" ] && [ -d \"$helper_transaction\" ] && helper_has_no_acl \"$helper_transaction\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_transaction\")\" = '0:0:700' ]; };"
  set validate_helper_base to "if [ -L /Library ] || [ ! -d /Library ] || [ -L " & helper_base_q & " ]; then exit 1; fi; if [ ! -e " & helper_base_q & " ]; then /bin/mkdir " & helper_base_q & "; /usr/sbin/chown root:wheel " & helper_base_q & "; /bin/chmod -N " & helper_base_q & "; /bin/chmod 0755 " & helper_base_q & "; fi; [ -d " & helper_base_q & " ] && helper_has_no_acl " & helper_base_q & " && [ \"$(/usr/bin/stat -f '%u' " & helper_base_q & ")\" = '0' ] || exit 1; helper_base_mode=$(/usr/bin/stat -f '%Lp' " & helper_base_q & "); case \"$helper_base_mode\" in ''|*[!0-7]*) exit 1;; esac; helper_base_bits=$((0$helper_base_mode)); if [ $((helper_base_bits & 0022)) -ne 0 ] && [ $((helper_base_bits & 01000)) -eq 0 ]; then exit 1; fi;"
  set prepare_paths to "helper_transaction=$(/usr/bin/mktemp -d " & helper_transaction_template_q & "); /usr/sbin/chown root:wheel \"$helper_transaction\"; /bin/chmod 0700 \"$helper_transaction\"; validate_helper_transaction; helper_stage=\"$helper_transaction/staged.bundle\"; helper_old=\"$helper_transaction/previous.bundle\"; helper_failed=\"$helper_transaction/failed.bundle\"; daemon_stage=" & daemon_plist_q & ".install-new.$$; daemon_old=" & daemon_plist_q & ".install-old.$$; agent_stage=" & agent_plist_q & ".install-new.$$; agent_old=" & agent_plist_q & ".install-old.$$; for install_path in \"$daemon_stage\" \"$daemon_old\" \"$agent_stage\" \"$agent_old\"; do if [ -e \"$install_path\" ] || [ -L \"$install_path\" ]; then exit 1; fi; done;"
  set stage_helper to "if [ -L " & service_source_q & " ] || [ ! -f " & service_source_q & " ]; then exit 1; fi; /bin/mkdir \"$helper_stage\" \"$helper_stage/Contents\" \"$helper_stage/Contents/MacOS\" \"$helper_stage/Contents/Resources\"; /bin/cp " & service_source_q & " \"$helper_stage/Contents/MacOS/service\"; if [ -e " & custom_source_q & " ] || [ -L " & custom_source_q & " ]; then [ ! -L " & custom_source_q & " ] && [ -f " & custom_source_q & " ] || exit 1; /bin/cp " & custom_source_q & " \"$helper_stage/Contents/Resources/custom.txt\"; fi; /bin/chmod -RN \"$helper_stage\"; /usr/sbin/chown -R root:wheel \"$helper_stage\"; /bin/chmod 0755 \"$helper_stage\" \"$helper_stage/Contents\" \"$helper_stage/Contents/MacOS\" \"$helper_stage/Contents/Resources\" \"$helper_stage/Contents/MacOS/service\"; if [ -f \"$helper_stage/Contents/Resources/custom.txt\" ]; then /bin/chmod 0600 \"$helper_stage/Contents/Resources/custom.txt\"; fi; validate_helper_tree \"$helper_stage\";"
  set stage_plists to "/usr/bin/printf '%s' " & quoted form of daemon_file & " > \"$daemon_stage\"; /usr/bin/printf '%s' " & quoted form of agent_file & " > \"$agent_stage\"; /usr/sbin/chown root:wheel \"$daemon_stage\" \"$agent_stage\"; /bin/chmod 0644 \"$daemon_stage\" \"$agent_stage\";"
  set stop_service to "daemon_existed=0; if [ -e " & daemon_plist_q & " ] || [ -L " & daemon_plist_q & " ]; then [ ! -L " & daemon_plist_q & " ] && [ -f " & daemon_plist_q & " ] || exit 1; daemon_existed=1; fi; daemon_was_loaded=0; if stopping_info=$(launchctl print system/" & daemon_label & " 2>/dev/null); then daemon_was_loaded=1; else stopping_info=''; fi; stopping_pid=$(printf '%s\n' \"$stopping_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); launchctl bootout system/" & daemon_label & " 2>/dev/null || launchctl unload -w " & daemon_plist_q & " 2>/dev/null || true;"
  set wait_for_stop to "service_stopped=0; service_stop_attempt=0; while [ \"$service_stop_attempt\" -lt 30 ]; do service_stop_attempt=$((service_stop_attempt + 1)); pid_gone=1; if [ -n \"$stopping_pid\" ] && kill -0 \"$stopping_pid\" 2>/dev/null; then pid_gone=0; fi; if [ \"$pid_gone\" -eq 1 ] && ! launchctl print system/" & daemon_label & " >/dev/null 2>&1; then service_stopped=1; break; fi; sleep 1; done; [ \"$service_stopped\" -eq 1 ];"
  set ensure_no_pending_migration to "if [ -e " & migration_state_q & " ] || [ -L " & migration_state_q & " ]; then echo 'PRIVILEGED_HELPER_MIGRATION_PENDING' >&2; exit 1; fi;"
  set lock_transaction to "if [ -e " & transaction_lock_q & " ] || [ -L " & transaction_lock_q & " ]; then [ ! -L " & transaction_lock_q & " ] && [ -f " & transaction_lock_q & " ] && [ \"$(/usr/bin/stat -f '%u' " & transaction_lock_q & ")\" = '0' ] || { echo 'UNSAFE_UPDATE_LOCK' >&2; exit 1; }; else umask 077; : > " & transaction_lock_q & "; /usr/sbin/chown root:wheel " & transaction_lock_q & "; fi; /bin/chmod -N " & transaction_lock_q & "; /bin/chmod 0600 " & transaction_lock_q & "; [ \"$(/usr/bin/stat -f '%u:%g:%Lp' " & transaction_lock_q & ")\" = '0:0:600' ] || exit 1; exec /usr/bin/lockf -knw -t 0 " & transaction_lock_q & " /bin/sh -c "
  set backup_installed to "if [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then validate_helper_tree " & helper_bundle_q & "; mv " & helper_bundle_q & " \"$helper_old\"; helper_backed_up=1; fi; if [ -e " & daemon_plist_q & " ] || [ -L " & daemon_plist_q & " ]; then [ ! -L " & daemon_plist_q & " ] && [ -f " & daemon_plist_q & " ] || exit 1; mv " & daemon_plist_q & " \"$daemon_old\"; daemon_backed_up=1; fi; if [ -e " & agent_plist_q & " ] || [ -L " & agent_plist_q & " ]; then [ ! -L " & agent_plist_q & " ] && [ -f " & agent_plist_q & " ] || exit 1; mv " & agent_plist_q & " \"$agent_old\"; agent_backed_up=1; fi;"
  set install_staged_helper to "mv \"$helper_stage\" " & helper_bundle_q & "; helper_swapped=1; validate_helper_tree " & helper_bundle_q & ";"
  set install_staged_plists to "mv \"$daemon_stage\" " & daemon_plist_q & "; daemon_swapped=1; mv \"$agent_stage\" " & agent_plist_q & "; agent_swapped=1;"
  set copy_preferences to "/bin/mkdir -p /var/root/Library/Preferences/com.carriez.RustDesk; for pref_source in " & prefs_toml_q & " " & prefs2_toml_q & "; do if [ -e \"$pref_source\" ] || [ -L \"$pref_source\" ]; then [ ! -L \"$pref_source\" ] && [ -f \"$pref_source\" ] || exit 1; /bin/cp \"$pref_source\" /var/root/Library/Preferences/com.carriez.RustDesk/; fi; done;"
  set load_service to "launchctl bootstrap system " & daemon_plist_q & " 2>/dev/null || launchctl load -w " & daemon_plist_q & ";"
  set service_ready_snapshot_function to "service_ready_snapshot() { expected_service_program=$(/usr/libexec/PlistBuddy -c 'Print :ProgramArguments:0' " & daemon_plist_q & ") || return 1; service_info=$(launchctl print system/" & daemon_label & " 2>/dev/null || true); service_pid=$(printf '%s\n' \"$service_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); service_program=$(printf '%s\n' \"$service_info\" | awk '/^[[:space:]]*program = / {print $3; exit}'); printf '%s\n' \"$service_info\" | grep -E '^[[:space:]]*state = running[[:space:]]*$' >/dev/null && [ -n \"$service_pid\" ] && [ -n \"$expected_service_program\" ] && [ \"$service_program\" = \"$expected_service_program\" ] && kill -0 \"$service_pid\" 2>/dev/null && [ ! -L " & quoted form of daemon_socket & " ] && [ \"$(/usr/bin/stat -f '%u' " & quoted form of daemon_socket & ")\" = '0' ] && [ -S " & quoted form of daemon_socket & " ] && /usr/bin/nc -zU " & quoted form of daemon_socket & "; };"
  set wait_for_service to "service_ready=0; service_ready_attempt=0; while [ \"$service_ready_attempt\" -lt 30 ]; do service_ready_attempt=$((service_ready_attempt + 1)); if service_ready_snapshot; then service_ready_pid=\"$service_pid\"; sleep 2; if service_ready_snapshot && [ \"$service_pid\" = \"$service_ready_pid\" ]; then service_ready=1; break; fi; fi; sleep 1; done; [ \"$service_ready\" -eq 1 ];"
  set stop_failed_service to "failed_stopping_info=$(launchctl print system/" & daemon_label & " 2>/dev/null || true); failed_stopping_pid=$(printf '%s\n' \"$failed_stopping_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); launchctl bootout system/" & daemon_label & " 2>/dev/null || launchctl unload -w " & daemon_plist_q & " 2>/dev/null || true;"
  set wait_for_failed_service_exit to "failed_service_stopped=0; failed_service_stop_attempt=0; while [ \"$failed_service_stop_attempt\" -lt 30 ]; do failed_service_stop_attempt=$((failed_service_stop_attempt + 1)); failed_pid_gone=1; if [ -n \"$failed_stopping_pid\" ] && kill -0 \"$failed_stopping_pid\" 2>/dev/null; then failed_pid_gone=0; fi; if [ \"$failed_pid_gone\" -eq 1 ] && ! launchctl print system/" & daemon_label & " >/dev/null 2>&1; then failed_service_stopped=1; break; fi; sleep 1; done;"

  set rollback_helper to "if [ \"${helper_swapped:-0}\" -eq 1 ]; then if [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then if [ -e \"$helper_failed\" ] || [ -L \"$helper_failed\" ] || ! mv " & helper_bundle_q & " \"$helper_failed\"; then rollback_status=1; else helper_swapped=0; fi; else helper_swapped=0; fi; fi; if [ \"${helper_backed_up:-0}\" -eq 1 ]; then if ! validate_helper_tree \"$helper_old\"; then rollback_status=1; elif [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then rollback_status=1; elif ! mv \"$helper_old\" " & helper_bundle_q & "; then rollback_status=1; elif ! validate_helper_tree " & helper_bundle_q & "; then rollback_status=1; else helper_backed_up=0; fi; fi;"
  set rollback_plists to "if [ \"${daemon_swapped:-0}\" -eq 1 ]; then rm -f " & daemon_plist_q & " || rollback_status=1; fi; if [ \"${agent_swapped:-0}\" -eq 1 ]; then rm -f " & agent_plist_q & " || rollback_status=1; fi; if [ \"${daemon_backed_up:-0}\" -eq 1 ]; then mv \"$daemon_old\" " & daemon_plist_q & " || rollback_status=1; fi; if [ \"${agent_backed_up:-0}\" -eq 1 ]; then mv \"$agent_old\" " & agent_plist_q & " || rollback_status=1; fi;"
  set cleanup_staging to "for staging_path in \"${daemon_stage:-}\" \"${agent_stage:-}\"; do if [ -n \"$staging_path\" ] && { [ -e \"$staging_path\" ] || [ -L \"$staging_path\" ]; }; then rm -rf \"$staging_path\" || cleanup_status=1; fi; done; if [ -n \"${helper_transaction:-}\" ] && { [ -e \"$helper_transaction\" ] || [ -L \"$helper_transaction\" ]; }; then if [ \"${helper_swapped:-0}\" -eq 0 ] && [ \"${helper_backed_up:-0}\" -eq 0 ] && validate_helper_transaction; then rm -rf \"$helper_transaction\" || cleanup_status=1; else cleanup_status=1; fi; fi;"
  set restore_service to "if [ \"${daemon_existed:-0}\" -eq 1 ] && [ \"${daemon_was_loaded:-0}\" -eq 1 ]; then if ! launchctl bootstrap system " & daemon_plist_q & " 2>/dev/null && ! launchctl load -w " & daemon_plist_q & "; then rollback_status=1; else restored_ready=0; restored_ready_attempt=0; while [ \"$restored_ready_attempt\" -lt 30 ]; do restored_ready_attempt=$((restored_ready_attempt + 1)); if service_ready_snapshot; then restored_ready_pid=\"$service_pid\"; sleep 2; if service_ready_snapshot && [ \"$service_pid\" = \"$restored_ready_pid\" ]; then restored_ready=1; break; fi; fi; sleep 1; done; if [ \"$restored_ready\" -ne 1 ]; then rollback_status=1; fi; fi; fi;"
  set rollback_install to "status=$?; trap - EXIT; set +e; cleanup_status=0; if [ \"${transaction_started:-0}\" -eq 1 ] && [ \"${transaction_committed:-0}\" -ne 1 ]; then rollback_status=0;" & stop_failed_service & wait_for_failed_service_exit & "if [ \"$failed_service_stopped\" -eq 1 ]; then" & rollback_helper & rollback_plists & restore_service & "else rollback_status=1; fi; if [ \"$rollback_status\" -ne 0 ]; then status=1; fi; fi;" & cleanup_staging & "if [ \"$cleanup_status\" -ne 0 ] && [ \"${transaction_committed:-0}\" -ne 1 ]; then status=1; elif [ \"$cleanup_status\" -ne 0 ]; then echo 'INSTALL_CLEANUP_FAILED_AFTER_COMMIT'; fi; exit \"$status\";"
  set commit_install to "transaction_committed=1; cleanup_status=0; if ! rm -rf \"$daemon_old\" \"$agent_old\"; then cleanup_status=1; fi; helper_backed_up=0; helper_swapped=0; if ! validate_helper_transaction || ! rm -rf \"$helper_transaction\"; then cleanup_status=1; fi; if [ \"$cleanup_status\" -ne 0 ]; then echo 'INSTALL_CLEANUP_FAILED_AFTER_COMMIT'; fi;"

  set sh to "umask 077; set -e; transaction_started=0; transaction_committed=0; helper_transaction=''; helper_backed_up=0; helper_swapped=0; daemon_backed_up=0; daemon_swapped=0; agent_backed_up=0; agent_swapped=0; daemon_was_loaded=0; trap " & quoted form of rollback_install & " EXIT;" & validate_helper_function & service_ready_snapshot_function & validate_helper_base & prepare_paths & stage_helper & stage_plists & "transaction_started=1;" & stop_service & wait_for_stop & ensure_no_pending_migration & backup_installed & install_staged_helper & install_staged_plists & copy_preferences & load_service & wait_for_service & commit_install
  set sh to lock_transaction & quoted form of sh

  do shell script sh with prompt "RustDesk wants to install daemon and agent" with administrator privileges
end run
