set daemon_plist to "/Library/LaunchDaemons/com.carriez.RustDesk_service.plist"
set agent_plist to "/Library/LaunchAgents/com.carriez.RustDesk_server.plist"
set daemon_label to "com.carriez.RustDesk_service"
set daemon_socket to "/tmp/RustDesk-service/ipc_service"
set helper_base to "/Library/PrivilegedHelperTools"
set helper_bundle to "/Library/PrivilegedHelperTools/com.carriez.RustDesk_service.bundle"
set migration_state to "/Library/PrivilegedHelperTools/.com.carriez.RustDesk_service.migration"
set transaction_lock to "/var/run/com.carriez.service-maintenance.lock"
set daemon_plist_q to quoted form of daemon_plist
set agent_plist_q to quoted form of agent_plist
set helper_bundle_q to quoted form of helper_bundle
set migration_state_q to quoted form of migration_state
set transaction_lock_q to quoted form of transaction_lock
set helper_transaction_template_q to quoted form of (helper_base & "/.com.carriez.RustDesk_service.uninstall.XXXXXX")

set validate_helper_function to "helper_has_no_acl() { acl_mode=$(/bin/ls -lde \"$1\" | /usr/bin/awk 'NR == 1 { print $1 }') || return 1; [ -n \"$acl_mode\" ] || return 1; case \"$acl_mode\" in *+) return 1;; esac; }; validate_helper_tree() { helper_root=\"$1\"; [ ! -L /Library ] && [ -d /Library ] && [ ! -L /Library/PrivilegedHelperTools ] && [ -d /Library/PrivilegedHelperTools ] && helper_has_no_acl /Library/PrivilegedHelperTools && [ \"$(/usr/bin/stat -f '%u' /Library/PrivilegedHelperTools)\" = '0' ] || return 1; helper_base_mode=$(/usr/bin/stat -f '%Lp' /Library/PrivilegedHelperTools) || return 1; case \"$helper_base_mode\" in ''|*[!0-7]*) return 1;; esac; helper_base_bits=$((0$helper_base_mode)); if [ $((helper_base_bits & 0022)) -ne 0 ] && [ $((helper_base_bits & 01000)) -eq 0 ]; then return 1; fi; for helper_dir in \"$helper_root\" \"$helper_root/Contents\" \"$helper_root/Contents/MacOS\" \"$helper_root/Contents/Resources\"; do [ ! -L \"$helper_dir\" ] && [ -d \"$helper_dir\" ] && helper_has_no_acl \"$helper_dir\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_dir\")\" = '0:0:755' ] || return 1; done; helper_bin=\"$helper_root/Contents/MacOS/service\"; [ ! -L \"$helper_bin\" ] && [ -f \"$helper_bin\" ] && helper_has_no_acl \"$helper_bin\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_bin\")\" = '0:0:755' ] || return 1; helper_custom=\"$helper_root/Contents/Resources/custom.txt\"; if [ -e \"$helper_custom\" ] || [ -L \"$helper_custom\" ]; then [ ! -L \"$helper_custom\" ] && [ -f \"$helper_custom\" ] && helper_has_no_acl \"$helper_custom\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_custom\")\" = '0:0:600' ] || return 1; fi; }; validate_helper_transaction() { [ -n \"$helper_transaction\" ] && [ ! -L \"$helper_transaction\" ] && [ -d \"$helper_transaction\" ] && helper_has_no_acl \"$helper_transaction\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_transaction\")\" = '0:0:700' ]; };"
set daemon_ready_snapshot_function to "daemon_ready_snapshot() { expected_daemon_program=$(/usr/libexec/PlistBuddy -c 'Print :ProgramArguments:0' " & daemon_plist_q & ") || return 1; daemon_info=$(launchctl print system/" & daemon_label & " 2>/dev/null || true); daemon_pid=$(printf '%s\n' \"$daemon_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); daemon_program=$(printf '%s\n' \"$daemon_info\" | awk '/^[[:space:]]*program = / {print $3; exit}'); printf '%s\n' \"$daemon_info\" | grep -E '^[[:space:]]*state = running[[:space:]]*$' >/dev/null && [ -n \"$daemon_pid\" ] && [ -n \"$expected_daemon_program\" ] && [ \"$daemon_program\" = \"$expected_daemon_program\" ] && kill -0 \"$daemon_pid\" 2>/dev/null && [ ! -L " & quoted form of daemon_socket & " ] && [ \"$(/usr/bin/stat -f '%u' " & quoted form of daemon_socket & ")\" = '0' ] && [ -S " & quoted form of daemon_socket & " ] && /usr/bin/nc -zU " & quoted form of daemon_socket & "; };"
set prepare_paths to "helper_transaction=''; helper_old=''; helper_failed=''; if [ \"${helper_existed:-0}\" -eq 1 ]; then helper_transaction=$(/usr/bin/mktemp -d " & helper_transaction_template_q & "); /usr/sbin/chown root:wheel \"$helper_transaction\"; /bin/chmod 0700 \"$helper_transaction\"; validate_helper_transaction; helper_old=\"$helper_transaction/previous.bundle\"; helper_failed=\"$helper_transaction/failed.bundle\"; fi; daemon_old=" & daemon_plist_q & ".uninstall.$$; agent_old=" & agent_plist_q & ".uninstall.$$; for uninstall_path in \"$daemon_old\" \"$agent_old\"; do if [ -e \"$uninstall_path\" ] || [ -L \"$uninstall_path\" ]; then exit 1; fi; done;"
set validate_targets to "if [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then validate_helper_tree " & helper_bundle_q & "; helper_existed=1; fi; [ ! -L " & daemon_plist_q & " ] && [ -f " & daemon_plist_q & " ] || exit 1; [ ! -L " & agent_plist_q & " ] && [ -f " & agent_plist_q & " ] || exit 1;"
set stop_daemon to "if stopping_info=$(launchctl print system/" & daemon_label & " 2>/dev/null); then daemon_was_loaded=1; else stopping_info=''; fi; stopping_pid=$(printf '%s\n' \"$stopping_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); launchctl bootout system/" & daemon_label & " 2>/dev/null || launchctl unload -w " & daemon_plist_q & " 2>/dev/null || true;"
set wait_for_daemon_exit to "daemon_stopped=0; daemon_stop_attempt=0; while [ \"$daemon_stop_attempt\" -lt 30 ]; do daemon_stop_attempt=$((daemon_stop_attempt + 1)); pid_gone=1; if [ -n \"$stopping_pid\" ] && kill -0 \"$stopping_pid\" 2>/dev/null; then pid_gone=0; fi; if [ \"$pid_gone\" -eq 1 ] && ! launchctl print system/" & daemon_label & " >/dev/null 2>&1; then daemon_stopped=1; break; fi; sleep 1; done; [ \"$daemon_stopped\" -eq 1 ];"
set ensure_no_pending_migration to "if [ -e " & migration_state_q & " ] || [ -L " & migration_state_q & " ]; then echo 'PRIVILEGED_HELPER_MIGRATION_PENDING' >&2; exit 1; fi;"
set lock_transaction to "if [ -e " & transaction_lock_q & " ] || [ -L " & transaction_lock_q & " ]; then [ ! -L " & transaction_lock_q & " ] && [ -f " & transaction_lock_q & " ] && [ \"$(/usr/bin/stat -f '%u' " & transaction_lock_q & ")\" = '0' ] || { echo 'UNSAFE_UPDATE_LOCK' >&2; exit 1; }; else umask 077; : > " & transaction_lock_q & "; /usr/sbin/chown root:wheel " & transaction_lock_q & "; fi; /bin/chmod -N " & transaction_lock_q & "; /bin/chmod 0600 " & transaction_lock_q & "; [ \"$(/usr/bin/stat -f '%u:%g:%Lp' " & transaction_lock_q & ")\" = '0:0:600' ] || exit 1; exec /usr/bin/lockf -knw -t 0 " & transaction_lock_q & " /bin/sh -c "
set remove_helper to "if [ \"${helper_existed:-0}\" -eq 1 ]; then mv " & helper_bundle_q & " \"$helper_old\"; helper_moved=1; fi;"
set remove_plists to "mv " & daemon_plist_q & " \"$daemon_old\"; daemon_moved=1; mv " & agent_plist_q & " \"$agent_old\"; agent_moved=1;"
set restore_targets to "if [ \"${helper_moved:-0}\" -eq 1 ]; then if [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then if [ -e \"$helper_failed\" ] || [ -L \"$helper_failed\" ] || ! mv " & helper_bundle_q & " \"$helper_failed\"; then rollback_status=1; fi; fi; if ! validate_helper_tree \"$helper_old\"; then rollback_status=1; elif [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then rollback_status=1; elif ! mv \"$helper_old\" " & helper_bundle_q & "; then rollback_status=1; elif ! validate_helper_tree " & helper_bundle_q & "; then rollback_status=1; else helper_moved=0; fi; fi; if [ \"${daemon_moved:-0}\" -eq 1 ]; then mv \"$daemon_old\" " & daemon_plist_q & " || rollback_status=1; fi; if [ \"${agent_moved:-0}\" -eq 1 ]; then mv \"$agent_old\" " & agent_plist_q & " || rollback_status=1; fi;"
set restore_daemon to "if [ \"${daemon_was_loaded:-0}\" -eq 1 ]; then if ! launchctl print system/" & daemon_label & " >/dev/null 2>&1 && ! launchctl bootstrap system " & daemon_plist_q & " 2>/dev/null && ! launchctl load -w " & daemon_plist_q & "; then rollback_status=1; else restored_ready=0; restored_ready_attempt=0; while [ \"$restored_ready_attempt\" -lt 30 ]; do restored_ready_attempt=$((restored_ready_attempt + 1)); if daemon_ready_snapshot; then restored_ready_pid=\"$daemon_pid\"; sleep 2; if daemon_ready_snapshot && [ \"$daemon_pid\" = \"$restored_ready_pid\" ]; then restored_ready=1; break; fi; fi; sleep 1; done; if [ \"$restored_ready\" -ne 1 ]; then rollback_status=1; fi; fi; fi;"
set cleanup_helper_transaction to "if [ -n \"${helper_transaction:-}\" ] && { [ -e \"$helper_transaction\" ] || [ -L \"$helper_transaction\" ]; }; then if [ \"${helper_moved:-0}\" -eq 0 ] && validate_helper_transaction; then rm -rf \"$helper_transaction\" || cleanup_status=1; else cleanup_status=1; fi; fi;"
set rollback_uninstall to "status=$?; trap - EXIT; set +e; cleanup_status=0; if [ \"${transaction_committed:-0}\" -ne 1 ]; then rollback_status=0;" & restore_targets & restore_daemon & "if [ \"$rollback_status\" -ne 0 ]; then status=1; fi; fi;" & cleanup_helper_transaction & "if [ \"$cleanup_status\" -ne 0 ]; then status=1; fi; exit \"$status\";"
set commit_uninstall to "transaction_committed=1; cleanup_status=0; if [ -n \"$helper_transaction\" ]; then if validate_helper_transaction && rm -rf \"$helper_transaction\"; then helper_moved=0; else cleanup_status=1; fi; fi; rm -f \"$daemon_old\" \"$agent_old\" || cleanup_status=1; if [ \"$cleanup_status\" -ne 0 ]; then echo 'UNINSTALL_CLEANUP_FAILED_AFTER_COMMIT' >&2; exit 1; fi;"

set sh to "umask 077; set -e; transaction_committed=0; helper_existed=0; helper_moved=0; daemon_moved=0; agent_moved=0; daemon_was_loaded=0; helper_transaction=''; trap " & quoted form of rollback_uninstall & " EXIT;" & validate_helper_function & daemon_ready_snapshot_function & validate_targets & prepare_paths & stop_daemon & wait_for_daemon_exit & ensure_no_pending_migration & remove_helper & remove_plists & commit_uninstall
set sh to lock_transaction & quoted form of sh
do shell script sh with prompt "RustDesk wants to unload daemon" with administrator privileges
