on run {user, cur_pid, source_path, expected_sha256}

  set agent_plist to "/Library/LaunchAgents/com.carriez.RustDesk_server.plist"
  set daemon_plist to "/Library/LaunchDaemons/com.carriez.RustDesk_service.plist"
  set app_bundle to "/Applications/RustDesk.app"
  set helper_base to "/Library/PrivilegedHelperTools"
  set helper_bundle to "/Library/PrivilegedHelperTools/com.carriez.RustDesk_service.bundle"
  set helper_service to helper_bundle & "/Contents/MacOS/service"
  set migration_state to "/Library/PrivilegedHelperTools/.com.carriez.RustDesk_service.migration"
  set transaction_lock to "/var/run/com.carriez.service-maintenance.lock"
  set daemon_label to "com.carriez.RustDesk_service"
  set daemon_socket to "/tmp/RustDesk-service/ipc_service"
  set readiness_attempts to "30"
  set write_plist_attempts to "60"

  set source_path_q to quoted form of source_path
  set expected_sha256_q to quoted form of expected_sha256
  set daemon_plist_q to quoted form of daemon_plist
  set daemon_target_q to quoted form of ("system/" & daemon_label)
  set helper_base_q to quoted form of helper_base
  set helper_bundle_q to quoted form of helper_bundle
  set helper_service_q to quoted form of helper_service
  set migration_state_q to quoted form of migration_state
  set transaction_lock_q to quoted form of transaction_lock
  set helper_transaction_template_q to quoted form of (helper_base & "/.com.carriez.RustDesk_service.update.XXXXXX")
  set check_source to "if [ -n " & expected_sha256_q & " ]; then test -f " & source_path_q & "; else test -d " & source_path_q & "; fi;"
  -- Official unattended bytes are authenticated by signed update metadata and SHA-256. Manual updates retain administrator authorization as their trust boundary; never add an unsigned fallback here.
  -- Rehash the root-owned copy in a clean environment before staging bytes.
  set prepare_verified to "verified_dir=$(/usr/bin/mktemp -d /tmp/.rustdeskupdate-verified.XXXXXX); /usr/sbin/chown root:wheel \"$verified_dir\"; /bin/chmod -N \"$verified_dir\"; /bin/chmod 0700 \"$verified_dir\"; verified_app=\"$verified_dir/RustDesk.app\"; dmg_attached=0; if [ -n " & expected_sha256_q & " ]; then verified_dmg=\"$verified_dir/update.dmg\"; /bin/cp " & source_path_q & " \"$verified_dmg\"; /usr/sbin/chown root:wheel \"$verified_dmg\"; /bin/chmod 0400 \"$verified_dmg\"; actual_sha256=$(/usr/bin/env -i /usr/bin/shasum -a 256 \"$verified_dmg\"); actual_sha256=${actual_sha256%% *}; if [ \"$actual_sha256\" != " & expected_sha256_q & " ]; then echo 'Update DMG SHA256 mismatch' >&2; exit 1; fi; dmg_mount=\"$verified_dir/mount\"; /bin/mkdir \"$dmg_mount\"; dmg_attached=1; /usr/bin/hdiutil attach -readonly -nobrowse -mountpoint \"$dmg_mount\" \"$verified_dmg\" >/dev/null; /usr/bin/ditto \"$dmg_mount/RustDesk.app\" \"$verified_app\"; /usr/bin/hdiutil detach \"$dmg_mount\" -force >/dev/null; dmg_attached=0; /bin/rm -f \"$verified_dmg\"; else /usr/bin/ditto " & source_path_q & " \"$verified_app\"; fi; /usr/sbin/chown -R root:wheel \"$verified_app\"; /bin/chmod -R go-w \"$verified_app\";"
  set ensure_atomic_bundle_swap to "verified_device=$(/usr/bin/stat -f '%d' \"$verified_dir\"); applications_device=$(/usr/bin/stat -f '%d' /Applications); [ -n \"$verified_device\" ] && [ \"$verified_device\" = \"$applications_device\" ] || { echo 'APP_UPDATE_REQUIRES_ONE_FILESYSTEM' >&2; exit 1; };"
  set resolve_uid to "uid=$(id -u " & quoted form of user & ");"
  set capture_stopping_jobs to "stopping_service_info=$(launchctl print " & daemon_target_q & " 2>/dev/null || true); stopping_service_pid=$(printf '%s\n' \"$stopping_service_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); stopping_agent_info=$(launchctl print \"gui/$uid/$agent_label\" 2>/dev/null || launchctl print \"user/$uid/$agent_label\" 2>/dev/null || launchctl print \"system/$agent_label\" 2>/dev/null || true); stopping_agent_pid=$(printf '%s\n' \"$stopping_agent_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}');"
  set unload_agent to "if [ -n \"$uid\" ]; then launchctl bootout gui/$uid " & quoted form of agent_plist & " 2>/dev/null || launchctl bootout user/$uid " & quoted form of agent_plist & " 2>/dev/null || launchctl unload -w " & quoted form of agent_plist & " || true; else launchctl unload -w " & quoted form of agent_plist & " || true; fi;"
  set unload_service to "launchctl bootout " & daemon_target_q & " 2>/dev/null || launchctl unload -w " & daemon_plist_q & " 2>/dev/null || true;"
  set kill_others to "pids=$(pgrep -x 'RustDesk' | grep -vx " & cur_pid & " || true); if [ -n \"$pids\" ]; then echo \"$pids\" | xargs kill -9 || true; fi;"
  set wait_for_stopped_jobs to "wait_for_stopped_jobs() { jobs_stopped=0; stop_attempt=0; while [ \"$stop_attempt\" -lt " & readiness_attempts & " ]; do stop_attempt=$((stop_attempt + 1)); service_pid_gone=1; if [ -n \"$stopping_service_pid\" ] && kill -0 \"$stopping_service_pid\" 2>/dev/null; then service_pid_gone=0; fi; agent_pid_gone=1; if [ -n \"$stopping_agent_pid\" ] && kill -0 \"$stopping_agent_pid\" 2>/dev/null; then agent_pid_gone=0; fi; remaining_pids=$(pgrep -x 'RustDesk' | grep -vx " & cur_pid & " || true); if [ \"$service_pid_gone\" -eq 1 ] && [ \"$agent_pid_gone\" -eq 1 ] && [ -z \"$remaining_pids\" ] && ! launchctl print " & daemon_target_q & " >/dev/null 2>&1 && ! launchctl print \"gui/$uid/$agent_label\" >/dev/null 2>&1 && ! launchctl print \"user/$uid/$agent_label\" >/dev/null 2>&1 && ! launchctl print \"system/$agent_label\" >/dev/null 2>&1; then jobs_stopped=1; break; fi; sleep 1; done; [ \"$jobs_stopped\" -eq 1 ]; };"
  set ensure_no_pending_migration to "if [ -e " & migration_state_q & " ] || [ -L " & migration_state_q & " ]; then echo 'PRIVILEGED_HELPER_MIGRATION_PENDING' >&2; exit 1; fi;"
  set lock_transaction to "if [ -e " & transaction_lock_q & " ] || [ -L " & transaction_lock_q & " ]; then [ ! -L " & transaction_lock_q & " ] && [ -f " & transaction_lock_q & " ] && [ \"$(/usr/bin/stat -f '%u' " & transaction_lock_q & ")\" = '0' ] || { echo 'UNSAFE_UPDATE_LOCK' >&2; exit 1; }; else umask 077; : > " & transaction_lock_q & "; /usr/sbin/chown root:wheel " & transaction_lock_q & "; fi; /bin/chmod -N " & transaction_lock_q & "; /bin/chmod 0600 " & transaction_lock_q & "; [ \"$(/usr/bin/stat -f '%u:%g:%Lp' " & transaction_lock_q & ")\" = '0:0:600' ] || exit 1; exec /usr/bin/lockf -knw -t 0 " & transaction_lock_q & " /bin/sh -c "

  set validate_helper_function to "helper_has_no_acl() { acl_mode=$(/bin/ls -lde \"$1\" | /usr/bin/awk 'NR == 1 { print $1 }') || return 1; [ -n \"$acl_mode\" ] || return 1; case \"$acl_mode\" in *+) return 1;; esac; }; validate_helper_tree() { helper_root=\"$1\"; for helper_dir in \"$helper_root\" \"$helper_root/Contents\" \"$helper_root/Contents/MacOS\" \"$helper_root/Contents/Resources\"; do [ ! -L \"$helper_dir\" ] && [ -d \"$helper_dir\" ] && helper_has_no_acl \"$helper_dir\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_dir\")\" = '0:0:755' ] || return 1; done; helper_bin=\"$helper_root/Contents/MacOS/service\"; [ ! -L \"$helper_bin\" ] && [ -f \"$helper_bin\" ] && helper_has_no_acl \"$helper_bin\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_bin\")\" = '0:0:755' ] || return 1; helper_custom=\"$helper_root/Contents/Resources/custom.txt\"; if [ -e \"$helper_custom\" ] || [ -L \"$helper_custom\" ]; then [ ! -L \"$helper_custom\" ] && [ -f \"$helper_custom\" ] && helper_has_no_acl \"$helper_custom\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_custom\")\" = '0:0:600' ] || return 1; fi; }; validate_helper_transaction() { [ -n \"$helper_transaction\" ] && [ ! -L \"$helper_transaction\" ] && [ -d \"$helper_transaction\" ] && helper_has_no_acl \"$helper_transaction\" && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$helper_transaction\")\" = '0:0:700' ]; };"
  set validate_helper_base to "if [ -L /Library ] || [ ! -d /Library ] || [ -L " & helper_base_q & " ]; then echo 'Unsafe privileged helper ancestor' >&2; exit 1; fi; if [ ! -e " & helper_base_q & " ]; then /bin/mkdir " & helper_base_q & "; /usr/sbin/chown root:wheel " & helper_base_q & "; /bin/chmod -N " & helper_base_q & "; /bin/chmod 0755 " & helper_base_q & "; fi; if [ ! -d " & helper_base_q & " ] || ! helper_has_no_acl " & helper_base_q & " || [ \"$(/usr/bin/stat -f '%u' " & helper_base_q & ")\" != '0' ]; then echo 'Privileged helper directory is not root-owned or has an ACL' >&2; exit 1; fi; helper_base_mode=$(/usr/bin/stat -f '%Lp' " & helper_base_q & "); case \"$helper_base_mode\" in ''|*[!0-7]*) exit 1;; esac; helper_base_bits=$((0$helper_base_mode)); if [ $((helper_base_bits & 0022)) -ne 0 ] && [ $((helper_base_bits & 01000)) -eq 0 ]; then echo 'Writable privileged helper directory lacks sticky bit' >&2; exit 1; fi;"
  set prepare_swap_paths to "temp_bundle=\"$verified_dir/staged.app\"; old_bundle=\"$verified_dir/previous.app\"; helper_transaction=$(/usr/bin/mktemp -d " & helper_transaction_template_q & "); /usr/sbin/chown root:wheel \"$helper_transaction\"; /bin/chmod 0700 \"$helper_transaction\"; validate_helper_transaction; temp_helper=\"$helper_transaction/staged.bundle\"; old_helper=\"$helper_transaction/previous.bundle\"; failed_helper=\"$helper_transaction/failed.bundle\";"
  set reject_swap_paths to "for swap_path in \"$temp_bundle\" \"$old_bundle\"; do if [ -e \"$swap_path\" ] || [ -L \"$swap_path\" ]; then echo 'Update recovery path already exists' >&2; exit 1; fi; done;"
  set backup_plists to "daemon_plist_backup=\"$verified_dir/daemon.plist\"; agent_plist_backup=\"$verified_dir/agent.plist\"; daemon_plist_existed=0; agent_plist_existed=0; if [ -e " & daemon_plist_q & " ] || [ -L " & daemon_plist_q & " ]; then [ ! -L " & daemon_plist_q & " ] && [ -f " & daemon_plist_q & " ] || { echo 'Refusing symlink plist backup source' >&2; exit 1; }; cp -p " & daemon_plist_q & " \"$daemon_plist_backup\"; daemon_plist_existed=1; fi; if [ -e " & quoted form of agent_plist & " ] || [ -L " & quoted form of agent_plist & " ]; then [ ! -L " & quoted form of agent_plist & " ] && [ -f " & quoted form of agent_plist & " ] || { echo 'Refusing symlink plist backup source' >&2; exit 1; }; cp -p " & quoted form of agent_plist & " \"$agent_plist_backup\"; agent_plist_existed=1; fi;"
  set restore_plist_function to "restore_plist_atomically() { restore_source=\"$1\"; restore_target=\"$2\"; restore_stage=\"$restore_target.rollback.$$\"; [ ! -e \"$restore_stage\" ] && [ ! -L \"$restore_stage\" ] || return 1; if ! /bin/cp -p \"$restore_source\" \"$restore_stage\" || ! /usr/sbin/chown root:wheel \"$restore_stage\" || ! /bin/chmod -N \"$restore_stage\" || ! /bin/chmod 0644 \"$restore_stage\" || ! /bin/mv \"$restore_stage\" \"$restore_target\"; then /bin/rm -f \"$restore_stage\"; return 1; fi; [ ! -L \"$restore_target\" ] && [ -f \"$restore_target\" ] && [ \"$(/usr/bin/stat -f '%u:%g:%Lp' \"$restore_target\")\" = '0:0:644' ]; };"
  set stage_bundle to "ditto \"$verified_app\" \"$temp_bundle\";"
  set protect_staged_bundle to "chown -R root:wheel \"$temp_bundle\"; chmod -R go-w \"$temp_bundle\"; (xattr -r -d com.apple.quarantine \"$temp_bundle\" || true);"
  set stage_helper to "helper_source=\"$verified_app/Contents/MacOS/service\"; custom_source=\"$verified_app/Contents/Resources/custom.txt\"; if [ -L \"$helper_source\" ] || [ ! -f \"$helper_source\" ]; then echo 'Invalid helper source' >&2; exit 1; fi; /bin/mkdir \"$temp_helper\" \"$temp_helper/Contents\" \"$temp_helper/Contents/MacOS\" \"$temp_helper/Contents/Resources\"; /bin/cp \"$helper_source\" \"$temp_helper/Contents/MacOS/service\"; if [ -e \"$custom_source\" ] || [ -L \"$custom_source\" ]; then if [ -L \"$custom_source\" ] || [ ! -f \"$custom_source\" ]; then echo 'Invalid custom.txt source' >&2; exit 1; fi; /bin/cp \"$custom_source\" \"$temp_helper/Contents/Resources/custom.txt\"; fi; /bin/chmod -RN \"$temp_helper\"; /usr/sbin/chown -R root:wheel \"$temp_helper\"; /bin/chmod 0755 \"$temp_helper\" \"$temp_helper/Contents\" \"$temp_helper/Contents/MacOS\" \"$temp_helper/Contents/Resources\" \"$temp_helper/Contents/MacOS/service\"; if [ -f \"$temp_helper/Contents/Resources/custom.txt\" ]; then /bin/chmod 0600 \"$temp_helper/Contents/Resources/custom.txt\"; fi; validate_helper_tree \"$temp_helper\";"
  set move_current_bundle to "if [ -e " & quoted form of app_bundle & " ]; then mv " & quoted form of app_bundle & " \"$old_bundle\"; bundle_backed_up=1; fi;"
  set install_staged_bundle to "staged_bundle_identity=$(/usr/bin/stat -f '%d:%i' \"$temp_bundle\"); mv \"$temp_bundle\" " & quoted form of app_bundle & "; bundle_swapped=1; installed_bundle_identity=$(/usr/bin/stat -f '%d:%i' " & quoted form of app_bundle & "); [ \"$installed_bundle_identity\" = \"$staged_bundle_identity\" ];"
  set move_current_helper to "if [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then validate_helper_tree " & helper_bundle_q & "; mv " & helper_bundle_q & " \"$old_helper\"; helper_backed_up=1; fi;"
  set install_staged_helper to "mv \"$temp_helper\" " & helper_bundle_q & "; helper_swapped=1; validate_helper_tree " & helper_bundle_q & ";"
  set rollback_bundle to "if [ \"${bundle_backed_up:-0}\" -eq 1 ]; then if [ ! -e \"$old_bundle\" ]; then rollback_status=1; elif ! rm -rf " & quoted form of app_bundle & "; then rollback_status=1; elif ! mv \"$old_bundle\" " & quoted form of app_bundle & "; then rollback_status=1; fi; elif [ \"${bundle_swapped:-0}\" -eq 1 ]; then rm -rf " & quoted form of app_bundle & " || rollback_status=1; fi;"
  set rollback_helper to "if [ \"${helper_swapped:-0}\" -eq 1 ]; then if [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then if [ -e \"$failed_helper\" ] || [ -L \"$failed_helper\" ] || ! mv " & helper_bundle_q & " \"$failed_helper\"; then rollback_status=1; else helper_swapped=0; fi; else helper_swapped=0; fi; fi; if [ \"${helper_backed_up:-0}\" -eq 1 ]; then if ! validate_helper_tree \"$old_helper\"; then rollback_status=1; elif [ -e " & helper_bundle_q & " ] || [ -L " & helper_bundle_q & " ]; then rollback_status=1; elif ! mv \"$old_helper\" " & helper_bundle_q & "; then rollback_status=1; elif ! validate_helper_tree " & helper_bundle_q & "; then rollback_status=1; else helper_backed_up=0; fi; fi;"
  set rollback_plists to "if [ \"${plists_swapped:-0}\" -eq 1 ]; then if [ \"${daemon_plist_existed:-0}\" -eq 1 ]; then restore_plist_atomically \"$daemon_plist_backup\" " & daemon_plist_q & " || rollback_status=1; else rm -f " & daemon_plist_q & " || rollback_status=1; fi; if [ \"${agent_plist_existed:-0}\" -eq 1 ]; then restore_plist_atomically \"$agent_plist_backup\" " & quoted form of agent_plist & " || rollback_status=1; else rm -f " & quoted form of agent_plist & " || rollback_status=1; fi; fi;"
  set cleanup_verified to "if [ \"${dmg_attached:-0}\" -eq 1 ]; then /usr/bin/hdiutil detach \"$dmg_mount\" -force >/dev/null 2>&1 || cleanup_status=1; fi; if [ -n \"${temp_bundle:-}\" ]; then rm -rf \"$temp_bundle\" || cleanup_status=1; fi; if [ -n \"${helper_transaction:-}\" ] && { [ -e \"$helper_transaction\" ] || [ -L \"$helper_transaction\" ]; }; then if [ \"${helper_swapped:-0}\" -eq 0 ] && [ \"${helper_backed_up:-0}\" -eq 0 ] && validate_helper_transaction; then rm -rf \"$helper_transaction\" || cleanup_status=1; else cleanup_status=1; fi; fi; if [ -n \"${verified_dir:-}\" ]; then rm -rf \"$verified_dir\" || cleanup_status=1; fi;"

  -- Generate plist definitions from the installed release that will run them.
  set write_new_plists to "write_new_plists() { plists_swapped=1; " & helper_service_q & " --write-plists & write_pid=$!; plist_write_attempt=0; while [ \"$plist_write_attempt\" -lt " & write_plist_attempts & " ]; do plist_write_attempt=$((plist_write_attempt + 1)); if ! kill -0 \"$write_pid\" 2>/dev/null; then wait \"$write_pid\"; return $?; fi; sleep 1; done; kill -TERM \"$write_pid\" 2>/dev/null || true; sleep 1; kill -KILL \"$write_pid\" 2>/dev/null || true; wait \"$write_pid\" 2>/dev/null || true; return 124; }; write_new_plists;"
  set load_service to "launchctl load -w " & daemon_plist_q & ";"
  set agent_label_cmd to "agent_label=$(basename " & quoted form of agent_plist & " .plist);"
  -- Agent load failure must trigger rollback; restoration remains best effort.
  set bootstrap_agent to "if [ -n \"$uid\" ]; then launchctl bootstrap gui/$uid " & quoted form of agent_plist & " 2>/dev/null || launchctl bootstrap user/$uid " & quoted form of agent_plist & " 2>/dev/null || launchctl load -w " & quoted form of agent_plist & "; else launchctl load -w " & quoted form of agent_plist & "; fi;"
  set kickstart_agent to "if [ -n \"$uid\" ]; then launchctl kickstart -k \"gui/$uid/$agent_label\" 2>/dev/null || launchctl kickstart -k \"user/$uid/$agent_label\" 2>/dev/null || true; fi;"
  set load_agent to bootstrap_agent & kickstart_agent
  -- Registration can succeed before a job is ready; keep rollback until both IPC sockets are live.
  set check_service to "expected_service_program=$(/usr/libexec/PlistBuddy -c 'Print :ProgramArguments:0' " & daemon_plist_q & "); service_info=$(launchctl print " & daemon_target_q & " 2>/dev/null || true); service_pid=$(printf '%s\n' \"$service_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); service_program=$(printf '%s\n' \"$service_info\" | awk '/^[[:space:]]*program = / {print $3; exit}'); printf '%s\n' \"$service_info\" | grep -E '^[[:space:]]*state = running[[:space:]]*$' >/dev/null && [ -n \"$service_pid\" ] && [ -n \"$expected_service_program\" ] && [ \"$service_program\" = \"$expected_service_program\" ] && kill -0 \"$service_pid\" 2>/dev/null && [ ! -L " & quoted form of daemon_socket & " ] && [ \"$(/usr/bin/stat -f '%u' " & quoted form of daemon_socket & ")\" = '0' ] && [ -S " & quoted form of daemon_socket & " ] && /usr/bin/nc -zU " & quoted form of daemon_socket
  set check_agent to "agent_info=$(launchctl print \"gui/$uid/$agent_label\" 2>/dev/null || launchctl print \"user/$uid/$agent_label\" 2>/dev/null || launchctl print \"system/$agent_label\" 2>/dev/null || true); agent_pid=$(printf '%s\n' \"$agent_info\" | awk '/^[[:space:]]*pid = / {print $3; exit}'); agent_process_uid=$(ps -p \"$agent_pid\" -o uid= 2>/dev/null | tr -d '[:space:]'); agent_process_args=$(ps -p \"$agent_pid\" -o args= 2>/dev/null || true); printf '%s\n' \"$agent_info\" | grep -E '^[[:space:]]*state = running[[:space:]]*$' >/dev/null && [ -n \"$agent_pid\" ] && kill -0 \"$agent_pid\" 2>/dev/null && [ \"$agent_process_uid\" = \"$uid\" ] && printf '%s\n' \"$agent_process_args\" | grep -F '/Applications/RustDesk.app/Contents/MacOS/RustDesk' >/dev/null && printf '%s\n' \"$agent_process_args\" | grep -E '(^|[[:space:]])--server([[:space:]]|$)' >/dev/null && [ ! -L \"/tmp/RustDesk-$uid/ipc\" ] && [ \"$(/usr/bin/stat -f '%u' \"/tmp/RustDesk-$uid/ipc\")\" = \"$uid\" ] && [ -S \"/tmp/RustDesk-$uid/ipc\" ] && /usr/bin/nc -zU \"/tmp/RustDesk-$uid/ipc\""
  set wait_for_service to "service_ready=0; service_ready_attempt=0; while [ \"$service_ready_attempt\" -lt " & readiness_attempts & " ]; do service_ready_attempt=$((service_ready_attempt + 1)); if " & check_service & "; then service_ready_pid=\"$service_pid\"; sleep 2; if " & check_service & " && [ \"$service_pid\" = \"$service_ready_pid\" ]; then service_ready=1; break; fi; fi; sleep 1; done; [ \"$service_ready\" -eq 1 ];"
  set wait_for_agent to "agent_ready=0; agent_ready_attempt=0; while [ \"$agent_ready_attempt\" -lt " & readiness_attempts & " ]; do agent_ready_attempt=$((agent_ready_attempt + 1)); if " & check_agent & "; then agent_ready_pid=\"$agent_pid\"; sleep 2; if " & check_agent & " && [ \"$agent_pid\" = \"$agent_ready_pid\" ]; then agent_ready=1; break; fi; fi; sleep 1; done; [ \"$agent_ready\" -eq 1 ];"
  set verify_readiness to check_service & ";" & check_agent & ";"
  set restore_service to "launchctl load -w " & daemon_plist_q & " || rollback_status=1;"
  set restore_agent to "if [ -n \"$uid\" ]; then launchctl bootstrap gui/$uid " & quoted form of agent_plist & " 2>/dev/null || launchctl bootstrap user/$uid " & quoted form of agent_plist & " 2>/dev/null || launchctl load -w " & quoted form of agent_plist & " || rollback_status=1; else launchctl load -w " & quoted form of agent_plist & " || rollback_status=1; fi;"
  set restored_readiness to wait_for_service & " || { echo 'RESTORED_UPDATE_READINESS_FAILED' >&2; rollback_status=1; };" & wait_for_agent & " || { echo 'RESTORED_UPDATE_READINESS_FAILED' >&2; rollback_status=1; };"
  set rollback_update to "status=$?; trap - EXIT; set +e; cleanup_status=0; if [ \"${transaction_started:-0}\" -eq 1 ] && [ \"${transaction_committed:-0}\" -ne 1 ]; then rollback_status=0; rollback_jobs_stopped=0;" & capture_stopping_jobs & unload_agent & unload_service & kill_others & "if wait_for_stopped_jobs; then rollback_jobs_stopped=1; fi; if [ \"$rollback_jobs_stopped\" -eq 1 ]; then" & rollback_bundle & rollback_helper & rollback_plists & restore_service & restore_agent & restored_readiness & "else rollback_status=1; fi; if [ \"$rollback_status\" -ne 0 ]; then status=1; fi; fi; if [ \"${rollback_status:-0}\" -eq 0 ]; then " & cleanup_verified & "fi; if [ \"$cleanup_status\" -ne 0 ] && [ \"${transaction_committed:-0}\" -ne 1 ]; then status=1; elif [ \"$cleanup_status\" -ne 0 ]; then echo 'UPDATE_CLEANUP_FAILED_AFTER_COMMIT'; fi; exit \"$status\";"
  set commit_update to "transaction_committed=1; helper_swapped=0; if ! rm -rf \"$old_bundle\"; then echo 'UPDATE_CLEANUP_FAILED_AFTER_COMMIT'; fi; if validate_helper_transaction && rm -rf \"$helper_transaction\"; then helper_backed_up=0; else echo 'UPDATE_CLEANUP_FAILED_AFTER_COMMIT'; fi;"

  set sh to "umask 077; set -e; transaction_started=0; transaction_committed=0; bundle_backed_up=0; bundle_swapped=0; helper_transaction=''; helper_backed_up=0; helper_swapped=0; plists_swapped=0;" & restore_plist_function & "trap " & quoted form of rollback_update & " EXIT;" & check_source & prepare_verified & ensure_atomic_bundle_swap & resolve_uid & validate_helper_function & validate_helper_base & wait_for_stopped_jobs & prepare_swap_paths & reject_swap_paths & backup_plists & agent_label_cmd & "transaction_started=1;" & stage_bundle & protect_staged_bundle & stage_helper & capture_stopping_jobs & unload_agent & unload_service & kill_others & "wait_for_stopped_jobs;" & ensure_no_pending_migration & move_current_bundle & install_staged_bundle & move_current_helper & install_staged_helper & write_new_plists & load_service & wait_for_service & load_agent & wait_for_agent & verify_readiness & commit_update
  set sh to lock_transaction & quoted form of sh

  do shell script sh with prompt "RustDesk wants to update itself" with administrator privileges
end run
